# Site settings
title: Exand
email: admin@admin.admin
description: "My name is Adam. I’m a UI/UX lead designer. I’ve helped companies like Google, Asics, Indeed or Tokyo Art Beat to create new digital products since 2013."
baseurl: "/portfolio" # the subpath of your site, e.g. /blog/
url: "https://exand.github.io/portfolio" # the base hostname & protocol for your site
ga: UA-45562731-1

# Build settings
markdown: kramdown

# Permalinks
permalink: none

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Custom collection
collections:
  work:
    output: true

# Plugin
plugins:
- jekyll-autoprefixer
